"""Concept axes for the full vendored role set.

Chosen to be semantically far apart: the previous set had two axes at cosine 0.98,
which wasted basis dimensions once orthogonalised. Each is a contrast between
groups of at least three roles so no single prompt dominates an axis.
"""
CONCEPTS = [
 ("fictional",   ["eldritch","leviathan","egregore","chimera","genie","wraith"],
                 ["auditor","accountant","scheduler","validator","proofreader"]),
 ("age",         ["ancient","elder","grandparent","retiree","veteran"],
                 ["infant","toddler","adolescent","teenager","student"]),
 ("nonhuman",    ["robot","golem","virus","swarm","hive","crystalline"],
                 ["doctor","lawyer","teacher","counselor","nutritionist"]),
 ("corporate",   ["accountant","auditor","consultant","analyst","coordinator"],
                 ["bohemian","hedonist","flaneur","dreamer","absurdist"]),
 ("solitude",    ["hermit","loner","exile","wanderer","ascetic"],
                 ["networker","collaborator","facilitator","host" ,"ambassador"]),
 ("danger",      ["predator","saboteur","criminal","destroyer","smuggler"],
                 ["caregiver","healer","peacekeeper","pacifist","guardian"]),
 ("interiority", ["philosopher","mystic","stoic","contemplative","oracle"],
                 ["dispatcher","coordinator","scheduler","organizer","planner"]),
 ("commerce",    ["merchant","auctioneer","marketer","entrepreneur","broker"],
                 ["ascetic","pilgrim","hermit","martyr","monk"]),
 ("artistry",    ["poet","composer","playwright","improviser","bard"],
                 ["auditor","proofreader","validator","grader","screener"]),
 ("authority",   ["judge","supervisor","warrior","commander","sovereign"],
                 ["prisoner","refugee","orphan","patient","prey"]),
 ("optimism",    ["optimist","altruist","idealist","evangelist","dreamer"],
                 ["cynic","skeptic","contrarian","nihilist","critic"]),
 ("nature",      ["tree","whale","coral_reef","ecosystem","mycorrhizal"],
                 ["programmer","debugger","engineer","technologist","statistician"]),
 ("displacement",["refugee","exile","immigrant","expatriate","nomad"],
                 ["provincial","traditionalist","parent","homeowner","native"]),
 ("performance", ["actor","celebrity","presenter","comedian","influencer"],
                 ["archivist","librarian","observer","witness","recluse"]),
 ("precision",   ["mathematician","statistician","physicist","chemist","analyst"],
                 ["absurdist","trickster","fool","improviser","dreamer"]),
 ("care",        ["caregiver","empath","therapist","counselor","healer"],
                 ["auditor","examiner","evaluator","competitor","predator"]),
 ("rebellion",   ["anarchist","rebel","revolutionary","provocateur","maverick"],
                 ["traditionalist","purist","moderator","conservator","validator"]),
 ("knowledge",   ["scholar","historian","researcher","archaeologist","librarian"],
                 ["gamer","surfer","daredevil","hedonist","celebrity"]),
]
